Repository prgrms-be-devcourse/NBE5-7-3-Team05, pull requests merged in 2025-06, with the labels that each got.

#8 Refactor : Follow 도메인 1차 코틀린 마이그레이션
  src/main/java/io/powerrangers/backend/controller/FollowController.java
  src/main/java/io/powerrangers/backend/controller/FollowController.kt
  src/main/java/io/powerrangers/backend/dao/FollowRepository.java
  src/main/java/io/powerrangers/backend/dao/FollowRepository.kt
  src/main/java/io/powerrangers/backend/dto/FollowCheckResponseDto.java
  src/main/java/io/powerrangers/backend/dto/FollowCheckResponseDto.kt
  src/main/java/io/powerrangers/backend/dto/FollowCountResponseDto.java
  src/main/java/io/powerrangers/backend/dto/FollowCountResponseDto.kt
  src/main/java/io/powerrangers/backend/dto/FollowRequestDto.java
  src/main/java/io/powerrangers/backend/dto/FollowRequestDto.kt
  src/main/java/io/powerrangers/backend/dto/FollowResponseDto.java
  src/main/java/io/powerrangers/backend/dto/FollowResponseDto.kt
  src/main/java/io/powerrangers/backend/entity/Follow.java
  src/main/java/io/powerrangers/backend/entity/Follow.kt
  src/main/java/io/powerrangers/backend/service/FollowService.java
  src/main/java/io/powerrangers/backend/service/FollowService.kt
  src/main/java/io/powerrangers/backend/utils/Extensions.kt
  src/main/resources/static/js/mypage.js
Labels: refactor, BE

#11 Refactor: Task 관련 클래스 코틀린으로 변환
  src/main/java/io/powerrangers/backend/config/S3Config.java
  src/main/java/io/powerrangers/backend/config/S3Config.kt
  src/main/java/io/powerrangers/backend/controller/TaskController.java
  src/main/java/io/powerrangers/backend/controller/TaskController.kt
  src/main/java/io/powerrangers/backend/dao/TaskRepository.java
  src/main/java/io/powerrangers/backend/dao/TaskRepository.kt
  src/main/java/io/powerrangers/backend/dto/Role.java
  src/main/java/io/powerrangers/backend/dto/TaskCreateRequestDto.java
  src/main/java/io/powerrangers/backend/dto/TaskCreateRequestDto.kt
  src/main/java/io/powerrangers/backend/dto/TaskImageResponseDto.java
  src/main/java/io/powerrangers/backend/dto/TaskImageResponseDto.kt
  src/main/java/io/powerrangers/backend/dto/TaskResponseDto.java
  src/main/java/io/powerrangers/backend/dto/TaskResponseDto.kt
  src/main/java/io/powerrangers/backend/dto/TaskScope.java
  src/main/java/io/powerrangers/backend/dto/TaskScope.kt
  src/main/java/io/powerrangers/backend/dto/TaskStatus.java
  src/main/java/io/powerrangers/backend/dto/TaskStatus.kt
  src/main/java/io/powerrangers/backend/dto/TaskSummaryResponseDto.java
  src/main/java/io/powerrangers/backend/dto/TaskSummaryResponseDto.kt
  src/main/java/io/powerrangers/backend/dto/TaskUpdateRequestDto.java
  src/main/java/io/powerrangers/backend/dto/TaskUpdateRequestDto.kt
  src/main/java/io/powerrangers/backend/entity/BaseEntity.java
  src/main/java/io/powerrangers/backend/entity/BaseEntity.kt
  src/main/java/io/powerrangers/backend/entity/Task.java
  src/main/java/io/powerrangers/backend/entity/Task.kt
  src/main/java/io/powerrangers/backend/service/S3Service.java
  src/main/java/io/powerrangers/backend/service/S3Service.kt
  src/main/java/io/powerrangers/backend/service/TaskService.java
  src/main/java/io/powerrangers/backend/service/TaskService.kt
Labels: refactor, BE

#13 Refactor: Comment도메인 코틀린 마이그레이션
  src/main/java/io/powerrangers/backend/controller/CommentController.java
  src/main/java/io/powerrangers/backend/controller/CommentController.kt
  src/main/java/io/powerrangers/backend/dao/CommentRepository.java
  src/main/java/io/powerrangers/backend/dao/CommentRepository.kt
  src/main/java/io/powerrangers/backend/dto/comment/CommentCreateRequestDto.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentCreateRequestDto.kt
  src/main/java/io/powerrangers/backend/dto/comment/CommentResponseDto.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentResponseDto.kt
  src/main/java/io/powerrangers/backend/dto/comment/CommentUpdateRequestDto.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentUpdateRequestDto.kt
  src/main/java/io/powerrangers/backend/dto/comment/CommentUpdateResponseDto.java
  src/main/java/io/powerrangers/backend/dto/comment/CommentUpdateResponseDto.kt
  src/main/java/io/powerrangers/backend/entity/Comment.java
  src/main/java/io/powerrangers/backend/entity/Comment.kt
  src/main/java/io/powerrangers/backend/service/CommentService.java
  src/main/java/io/powerrangers/backend/service/CommentService.kt
Labels: refactor, BE

#10 Refactor : 예외 관련 코드 코틀린 마이그레이션
  build.gradle
  src/main/java/io/powerrangers/backend/exception/AuthTokenException.java
  src/main/java/io/powerrangers/backend/exception/AuthTokenException.kt
  src/main/java/io/powerrangers/backend/exception/CustomException.java
  src/main/java/io/powerrangers/backend/exception/CustomException.kt
  src/main/java/io/powerrangers/backend/exception/CustomOAuth2AuthenticationFailureHandler.java
  src/main/java/io/powerrangers/backend/exception/CustomOAuth2AuthenticationFailureHandler.kt
  src/main/java/io/powerrangers/backend/exception/ErrorCode.kt
  src/main/java/io/powerrangers/backend/exception/GlobalExceptionHandler.java
  src/main/java/io/powerrangers/backend/exception/GlobalExceptionHandler.kt
Labels: refactor, BE

#12 Refactor : User 관련 클래스 코틀린으로 변환
  build.gradle
  src/main/java/io/powerrangers/backend/controller/UserController.java
  src/main/java/io/powerrangers/backend/controller/UserController.kt
  src/main/java/io/powerrangers/backend/dao/UserRepository.java
  src/main/java/io/powerrangers/backend/dao/UserRepository.kt
  src/main/java/io/powerrangers/backend/dto/UserFollowResponseDto.java
  src/main/java/io/powerrangers/backend/dto/UserFollowResponseDto.kt
  src/main/java/io/powerrangers/backend/dto/UserGetProfileResponseDto.java
  src/main/java/io/powerrangers/backend/dto/UserGetProfileResponseDto.kt
  src/main/java/io/powerrangers/backend/dto/UserUpdateProfileRequestDto.java
  src/main/java/io/powerrangers/backend/dto/UserUpdateProfileRequestDto.kt
  src/main/java/io/powerrangers/backend/entity/BaseEntity.kt
  src/main/java/io/powerrangers/backend/entity/User.java
  src/main/java/io/powerrangers/backend/entity/User.kt
  src/main/java/io/powerrangers/backend/service/UserService.java
  src/main/java/io/powerrangers/backend/service/UserService.kt
  src/main/java/io/powerrangers/backend/utils/Extensions.kt
Labels: refactor, BE

#23 Refactor : Task 관련 클래스 추가 수정
  src/main/java/io/powerrangers/backend/dto/TaskImageResponseDto.kt
  src/main/java/io/powerrangers/backend/dto/TaskResponseDto.kt
  src/main/java/io/powerrangers/backend/service/TaskService.kt
  src/main/java/io/powerrangers/backend/service/UserService.kt
  src/main/java/io/powerrangers/backend/utils/Extensions.kt
Labels: refactor, BE

#31 Refactor : commentdto 구조변경
  src/main/java/io/powerrangers/backend/controller/CommentController.kt
  src/main/java/io/powerrangers/backend/dto/CommentCreateRequestDto.kt
  src/main/java/io/powerrangers/backend/dto/CommentResponseDto.kt
  src/main/java/io/powerrangers/backend/dto/CommentUpdateRequestDto.kt
  src/main/java/io/powerrangers/backend/dto/CommentUpdateResponseDto.kt
  src/main/java/io/powerrangers/backend/service/CommentService.kt
  src/test/java/io/powerrangers/backend/service/CommentServiceTests.java
Labels: refactor, BE

#47 Test : CommentRepository 테스트코드 작성
  src/test/java/io/powerrangers/backend/repository/CommentRepositoryTests.kt
  src/test/java/io/powerrangers/backend/service/CommentServiceTests.java
Labels: feat, BE

#62 Test : FollowController 슬라이스 테스트 코드 작성
  src/test/java/io/powerrangers/backend/controller/FollowControllerTests.kt
  src/test/java/io/powerrangers/backend/utils/TestUtils.kt
Labels: test, BE

#50 Test : TaskService 테스트코드 작성
  build.gradle
  src/test/java/io/powerrangers/backend/service/TaskServiceTest.java
  src/test/java/io/powerrangers/backend/service/TaskServiceTests.kt
Labels: test, BE

#59 Refactor : getComments 함수 성능 개선
  src/main/java/io/powerrangers/backend/service/CommentService.kt
Labels: refactor, BE

#60 Test : CommentController 테스트코드 작성
  src/test/java/io/powerrangers/backend/controller/CommentControllerTests.kt
Labels: test, BE

#65 Test: CommentServiceTests 작성
  src/main/java/io/powerrangers/backend/entity/Comment.kt
  src/test/java/io/powerrangers/backend/service/CommentServiceTests.kt
Labels: test, BE

#63 Test: Jwt, CustomOauth2Service 테스트
  build.gradle
  src/main/java/io/powerrangers/backend/config/JwtAuthenticationFilter.kt
  src/main/java/io/powerrangers/backend/config/SecurityConfig.kt
  src/main/java/io/powerrangers/backend/service/CustomOauth2UserService.kt
  src/main/java/io/powerrangers/backend/service/JwtProvider.kt
  src/main/java/io/powerrangers/backend/service/UserService.kt
  src/test/java/io/powerrangers/backend/dao/RefreshTokenRepositoryAdapterTests.kt
  src/test/java/io/powerrangers/backend/service/CustomOauth2UserServiceTests.kt
  src/test/java/io/powerrangers/backend/service/JwtProviderTests.kt
Labels: test, BE

#76 Fix : Favicon.ico 추가해서 NoResourceFoundException 해결
  src/main/resources/static/favicon.ico
Labels: BE, Fix

#77 Refactor: BaseResponse 고도화
  src/main/java/io/powerrangers/backend/controller/CommentController.kt
  src/main/java/io/powerrangers/backend/controller/FollowController.kt
  src/main/java/io/powerrangers/backend/controller/TaskController.kt
  src/main/java/io/powerrangers/backend/controller/UserController.kt
  src/main/java/io/powerrangers/backend/dto/BaseResponse.kt
  src/main/java/io/powerrangers/backend/exception/GlobalExceptionHandler.kt
Labels: refactor, BE

#74 Feat: CI 빌드/테스트 자동화
  .github/workflows/ci.yml
  src/test/java/io/powerrangers/backend/BackendApplicationTests.kt
  src/test/resources/application-test.yml
Labels: feat, BE

#82 Feat: 채팅,팔로우 알림기능구현
  build.gradle
  src/main/java/io/powerrangers/backend/config/RedisConfig.kt
  src/main/java/io/powerrangers/backend/config/SecurityConfig.kt
  src/main/java/io/powerrangers/backend/controller/NotificationController.kt
  src/main/java/io/powerrangers/backend/dao/adapter/RedisSubscriber.kt
  src/main/java/io/powerrangers/backend/dto/Notification.kt
  src/main/java/io/powerrangers/backend/dto/NotificationType.kt
  src/main/java/io/powerrangers/backend/service/CommentService.kt
  src/main/java/io/powerrangers/backend/service/FollowService.kt
  src/main/java/io/powerrangers/backend/service/NotificationService.kt
  src/main/resources/static/follow-list.html
  src/main/resources/static/index.html
  src/main/resources/static/js/main.js
  src/main/resources/static/js/notification.js
  src/main/resources/static/search.html
  src/main/resources/static/user-page.html
  src/main/resources/static/user.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/updatemypage.html
  src/test/java/io/powerrangers/backend/BackendApplicationTests.kt
  src/test/java/io/powerrangers/backend/service/CommentServiceTests.kt
  src/test/java/io/powerrangers/backend/service/FollowServiceTests.kt
Labels: feat, BE

#84 Fix : PR 실패 시에도 슬랙 알람 가도록 수정
  .github/workflows/ci.yml
Labels: BE, Fix

#85 Fix: FrontEnd 버그 수정
  src/main/java/io/powerrangers/backend/utils/UserDetailsFactory.kt
  src/main/resources/static/follow-list.html
  src/main/resources/static/index.html
  src/main/resources/static/js/auth.js
  src/main/resources/static/js/follow.js
  src/main/resources/static/js/header.js
  src/main/resources/static/js/index.js
  src/main/resources/static/js/initial-auth.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/mypage.js
  src/main/resources/static/js/search.js
  src/main/resources/static/js/token-reissue.js
  src/main/resources/static/js/user-page.js
  src/main/resources/static/js/user.js
  src/main/resources/static/search.html
  src/main/resources/static/user.html
  src/main/resources/templates/mypage.html
  src/main/resources/templates/updatemypage.html
Labels: FE, Fix

#89 Feat: CD 자동화 코드 추가
  .github/workflows/ci-cd.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/java/io/powerrangers/backend/entity/User.kt
  src/test/java/io/powerrangers/backend/config/JwtAuthenticationFilterTest.kt
  src/test/resources/application-test.yml
Labels: feat, BE

#93 Fix : docker-compose.yml 파일 수정
  docker-compose.yml
Labels: BE, Fix
